apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hummingbot.fullname" . }}
  labels:
    {{- include "hummingbot.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "hummingbot.fullname" . }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "hummingbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "hummingbot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hummingbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "hummingbot.fullname" . }}-global
          configMap:
            name: {{ include "hummingbot.fullname" . }}-global
        - name: {{ include "hummingbot.fullname" . }}-logs
          configMap:
            name: {{ include "hummingbot.fullname" . }}-logs
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c 
            - tail -f /dev/null
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ include "hummingbot.fullname" . }}-global
              mountPath: /conf/conf_global.yaml
              subPath: conf_global.yaml
            - name: {{ include "hummingbot.fullname" . }}-logs
              mountPath: /conf/hummingbot_logs.yaml
              subPath: hummingbot_logs.yaml
            - name: hummingbot-pvc-data
              mountPath: /data
            - name: hummingbot-pvc-logs
              mountPath: /logs
            - name: hummingbot-pvc-scripts
              mountPath: /scripts
          env:
            {{- include "hummingbot.env" . | indent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: hummingbot-pvc-logs
      spec:
        accessModes:
        - {{ .Values.persistence.accessMode }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        resources:
          requests:
            storage: {{ .Values.persistence.logs.size }}
        volumeMode: Filesystem
    - metadata:
        name: hummingbot-pvc-data
      spec:
        accessModes:
        - {{ .Values.persistence.accessMode }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        resources:
          requests:
            storage: {{ .Values.persistence.data.size }}
        volumeMode: Filesystem
    - metadata:
        name: hummingbot-pvc-scripts
      spec:
        accessModes:
        - {{ .Values.persistence.accessMode }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        resources:
          requests:
            storage: {{ .Values.persistence.scripts.size }}
        volumeMode: Filesystem
